#spring.application.name=clinical-record-service
#server.port=8082
#
## Local Testing  Bypasses
#spring.config.import=optional:configserver:http://localhost:8888
#eureka.client.enabled=false
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#
## Local MongoDB Connection
#spring.mongodb.uri=mongodb://localhost:27017/clinical_db

spring.application.name=appointment-service
spring.config.import=optional:configserver:http://localhost:8888